# based on https://github.com/confluentinc/cp-all-in-one/tree/7.3.0-post/cp-all-in-one-kraft
---
version: '3'
services:
  db:
    image: postgres:15.3
    container_name: test-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initdb/test:/docker-entrypoint-initdb.d
    networks:
      - skynet

  zookeeper:
    container_name: zookeeper-beast
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - skynet

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-man
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - skynet

networks:
  skynet:
    ipam:
      config:
        - subnet: 172.16.7.0/24
